[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["3.8"]
version = ["22.3"]

[envs.default.overrides]
matrix.version.env-vars = [
  { key = "REDPANDA_VERSION", value = "v22.3.11", if = ["22.3"] },
]

[envs.default.env-vars]
DDEV_SKIP_GENERIC_TAGS_CHECK = "true"

[envs.default]
e2e-env = false
